// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agruotnpsxdgyydgpqge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFncnVvdG5wc3hkZ3l5ZGdwcWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NDQyOTcsImV4cCI6MjA2NjIyMDI5N30.xU6s3obC5QU_vIGuKDexNVzvABG1tGLWy6tDefES12g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);